name: Acceptance
on:
  workflow_dispatch:
    inputs:
      sentinel-policy-name:
        type: string
        description: "Name of the sentinel policy that needs to be tested"
        required: false
        default: ""

jobs:
  acceptance:
    uses: hashicorp/policy-library-workflows-common/.github/workflows/acceptance.yml@main
    with:
      tfc-organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
      tfc-project: ${{ vars.TF_CLOUD_PROJECT }}
      tfc-hostname: ${{ vars.TF_CLOUD_HOSTNAME }}
      sentinel-policy-name: ${{ inputs.sentinel-policy-name }}
    secrets: inherit